/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TeachersIndexImport } from './routes/teachers.index'
import { Route as CoursesIndexImport } from './routes/courses.index'
import { Route as TeachersCreateImport } from './routes/teachers_.create'
import { Route as TeachersIdImport } from './routes/teachers.$id'
import { Route as CoursesCreateImport } from './routes/courses_.create'
import { Route as CoursesIdImport } from './routes/courses.$id'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const TeachersIndexRoute = TeachersIndexImport.update({
  id: '/teachers/',
  path: '/teachers/',
  getParentRoute: () => rootRoute,
} as any)

const CoursesIndexRoute = CoursesIndexImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRoute,
} as any)

const TeachersCreateRoute = TeachersCreateImport.update({
  id: '/teachers_/create',
  path: '/teachers/create',
  getParentRoute: () => rootRoute,
} as any)

const TeachersIdRoute = TeachersIdImport.update({
  id: '/teachers/$id',
  path: '/teachers/$id',
  getParentRoute: () => rootRoute,
} as any)

const CoursesCreateRoute = CoursesCreateImport.update({
  id: '/courses_/create',
  path: '/courses/create',
  getParentRoute: () => rootRoute,
} as any)

const CoursesIdRoute = CoursesIdImport.update({
  id: '/courses/$id',
  path: '/courses/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/courses/$id': {
      id: '/courses/$id'
      path: '/courses/$id'
      fullPath: '/courses/$id'
      preLoaderRoute: typeof CoursesIdImport
      parentRoute: typeof rootRoute
    }
    '/courses_/create': {
      id: '/courses_/create'
      path: '/courses/create'
      fullPath: '/courses/create'
      preLoaderRoute: typeof CoursesCreateImport
      parentRoute: typeof rootRoute
    }
    '/teachers/$id': {
      id: '/teachers/$id'
      path: '/teachers/$id'
      fullPath: '/teachers/$id'
      preLoaderRoute: typeof TeachersIdImport
      parentRoute: typeof rootRoute
    }
    '/teachers_/create': {
      id: '/teachers_/create'
      path: '/teachers/create'
      fullPath: '/teachers/create'
      preLoaderRoute: typeof TeachersCreateImport
      parentRoute: typeof rootRoute
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesIndexImport
      parentRoute: typeof rootRoute
    }
    '/teachers/': {
      id: '/teachers/'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof TeachersIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/courses/$id': typeof CoursesIdRoute
  '/courses/create': typeof CoursesCreateRoute
  '/teachers/$id': typeof TeachersIdRoute
  '/teachers/create': typeof TeachersCreateRoute
  '/courses': typeof CoursesIndexRoute
  '/teachers': typeof TeachersIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/courses/$id': typeof CoursesIdRoute
  '/courses/create': typeof CoursesCreateRoute
  '/teachers/$id': typeof TeachersIdRoute
  '/teachers/create': typeof TeachersCreateRoute
  '/courses': typeof CoursesIndexRoute
  '/teachers': typeof TeachersIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/courses/$id': typeof CoursesIdRoute
  '/courses_/create': typeof CoursesCreateRoute
  '/teachers/$id': typeof TeachersIdRoute
  '/teachers_/create': typeof TeachersCreateRoute
  '/courses/': typeof CoursesIndexRoute
  '/teachers/': typeof TeachersIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/courses/$id'
    | '/courses/create'
    | '/teachers/$id'
    | '/teachers/create'
    | '/courses'
    | '/teachers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/courses/$id'
    | '/courses/create'
    | '/teachers/$id'
    | '/teachers/create'
    | '/courses'
    | '/teachers'
  id:
    | '__root__'
    | '/'
    | '/courses/$id'
    | '/courses_/create'
    | '/teachers/$id'
    | '/teachers_/create'
    | '/courses/'
    | '/teachers/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  CoursesIdRoute: typeof CoursesIdRoute
  CoursesCreateRoute: typeof CoursesCreateRoute
  TeachersIdRoute: typeof TeachersIdRoute
  TeachersCreateRoute: typeof TeachersCreateRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  TeachersIndexRoute: typeof TeachersIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  CoursesIdRoute: CoursesIdRoute,
  CoursesCreateRoute: CoursesCreateRoute,
  TeachersIdRoute: TeachersIdRoute,
  TeachersCreateRoute: TeachersCreateRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  TeachersIndexRoute: TeachersIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/courses/$id",
        "/courses_/create",
        "/teachers/$id",
        "/teachers_/create",
        "/courses/",
        "/teachers/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/courses/$id": {
      "filePath": "courses.$id.tsx"
    },
    "/courses_/create": {
      "filePath": "courses_.create.tsx"
    },
    "/teachers/$id": {
      "filePath": "teachers.$id.tsx"
    },
    "/teachers_/create": {
      "filePath": "teachers_.create.tsx"
    },
    "/courses/": {
      "filePath": "courses.index.tsx"
    },
    "/teachers/": {
      "filePath": "teachers.index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
