/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TeachersIndexImport } from './routes/teachers.index'
import { Route as CoursesIndexImport } from './routes/courses.index'
import { Route as TeachersCreateImport } from './routes/teachers_.create'
import { Route as TeachersIdImport } from './routes/teachers.$id'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const TeachersIndexRoute = TeachersIndexImport.update({
  path: '/teachers/',
  getParentRoute: () => rootRoute,
} as any)

const CoursesIndexRoute = CoursesIndexImport.update({
  path: '/courses/',
  getParentRoute: () => rootRoute,
} as any)

const TeachersCreateRoute = TeachersCreateImport.update({
  path: '/teachers/create',
  getParentRoute: () => rootRoute,
} as any)

const TeachersIdRoute = TeachersIdImport.update({
  path: '/teachers/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/teachers/$id': {
      preLoaderRoute: typeof TeachersIdImport
      parentRoute: typeof rootRoute
    }
    '/teachers/create': {
      preLoaderRoute: typeof TeachersCreateImport
      parentRoute: typeof rootRoute
    }
    '/courses/': {
      preLoaderRoute: typeof CoursesIndexImport
      parentRoute: typeof rootRoute
    }
    '/teachers/': {
      preLoaderRoute: typeof TeachersIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  TeachersIdRoute,
  TeachersCreateRoute,
  CoursesIndexRoute,
  TeachersIndexRoute,
])

/* prettier-ignore-end */
